spring.application.name=placementtracker


spring.datasource.url=jdbc:postgresql://ep-long-boat-ao4zmsv2-pooler.c-2.ap-southeast-1.aws.neon.tech/neondb?sslmode=require

spring.datasource.username=neondb_owner

spring.datasource.password=npg_CkSv7JNKM9IQ

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true